default:
  index:
    security: true
    credentials:
      - [Administrador]

insumo:
  index:
    security: true
    credentials:
      - [Administrador]
  new:
    security: true
    credentials:
      - Administrador

presentacion:
  index:
    security: true
    credentials:
      - Administrador
    